# Generated by Django 3.0 on 2019-12-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=1000)),
                ('start_date', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('bus_no', models.CharField(max_length=20)),
                ('alt_bus_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
                ('address2', models.CharField(max_length=1000)),
                ('bus_website', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('bus_logo', models.FileField(upload_to='media')),
            ],
            options={
                'db_table': 'information',
            },
        ),
    ]
